// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class IMAGE_DATA
    {
        public int ImageID { get; set; }
        public Guid FS_GUID { get; set; }
        public byte[] Data { get; set; }

        public virtual IMAGE Image { get; set; }
    }
}