// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    /// <summary>
    /// Test table for EF Core Cancellation Token
    /// </summary>
    public partial class IMAGE
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public virtual IMAGE_DATA IMAGE_DATA { get; set; }
    }
}